# Generated by Django 5.2.3 on 2025-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('materialtype', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='')),
            ],
        ),
    ]
