# Generated by Django 5.2.3 on 2025-06-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='response',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
