# Generated by Django 5.2.3 on 2025-06-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Enquirytext',
            new_name='enquirytext',
        ),
    ]
