# Generated by Django 5.2.3 on 2025-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0005_remove_logininfo_id_alter_logininfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='userid',
            field=models.CharField(max_length=50),
        ),
    ]
