# Generated by Django 5.2.3 on 2025-06-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0006_logininfo_id_alter_logininfo_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='userid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
